name: docker

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPOSITORY: demo-script
      IMAGE_TAG: latest
      DOCKER_SERVER: docker.io
      DOCKER_USER: rithwwik

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # Setup hardware emulator usingQEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

        # Setup Docker Buildx for multi-arch-images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Authenticate with Dockerhub using a Docker password-secret
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_REPOSITORY }}:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/{{ env.IMAGE_REPOSITORY }}:latest
