#dckr_pat_svduM6YQtXFF2SaVMAuxLcl8Nzg
name: release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release-docker-image:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPOSITORY: rithwwik/demo-script
      IMAGE_TAG: latest
      #DOCKER_SERVER: docker.io
      DOCKER_USER: rithwwik

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate with DockerHub
        run: |
          # Authenticate with Dockerhub using a Docker password secret
          docker login \
            -u ${{ env.DOCKER_USER }} \
            -p "${{ secrets.DOCKER_PASSWORD }}"

     
