name: ci
on:
  push:
    branches: [ "main" ]
  paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]
  paths-ignore:
      - "doc/**"
      - "**.md"

defaults:
  run:
    shell: bash

jobs:
  develop-pr-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate with DockerHub
        run: |
              secrets:
                dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
                dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
